import type { KeyboardActionDefinition, KeyboardShortcutPreset } from "./registry";

export const COVE_KEYBOARD_PRESET_ID = "cove:native";
export const STASH_KEYBOARD_PRESET_ID = "cove:stash-v0.31.1";
export const DISABLED_KEYBOARD_PRESET_ID = "cove:disabled";

export const COVE_KEYBOARD_ACTIONS: KeyboardActionDefinition[] = [
  { id: "global.shortcuts", group: "Global", label: "Keyboard shortcuts", defaultBindings: ["?"] },
  { id: "global.help", group: "Global", label: "Help and tutorials", defaultBindings: [] },
  { id: "global.home", group: "Global Navigation", label: "Home", defaultBindings: ["g h"] },
  { id: "global.videos", group: "Global Navigation", label: "Videos", defaultBindings: ["g s"] },
  { id: "global.audios", group: "Global Navigation", label: "Audios", defaultBindings: ["g a"] },
  { id: "global.texts", group: "Global Navigation", label: "Texts", defaultBindings: ["g x"] },
  { id: "global.segments", group: "Global Navigation", label: "Segments", defaultBindings: ["g m"] },
  { id: "global.faces", group: "Global Navigation", label: "Faces", defaultBindings: ["g f"] },
  { id: "global.images", group: "Global Navigation", label: "Images", defaultBindings: ["g i"] },
  { id: "global.groups", group: "Global Navigation", label: "Groups", defaultBindings: ["g v"] },
  { id: "global.galleries", group: "Global Navigation", label: "Galleries", defaultBindings: ["g l"] },
  { id: "global.performers", group: "Global Navigation", label: "Performers", defaultBindings: ["g p"] },
  { id: "global.studios", group: "Global Navigation", label: "Studios", defaultBindings: ["g u"] },
  { id: "global.tags", group: "Global Navigation", label: "Tags", defaultBindings: ["g t"] },
  { id: "global.settings", group: "Global Navigation", label: "Settings", defaultBindings: ["g z"] },
  { id: "global.stats", group: "Global Navigation", label: "Stats", defaultBindings: ["g d"] },
  { id: "list.search", group: "List Pages", label: "Focus search", defaultBindings: ["/"] },
  { id: "list.view.grid", group: "List Pages", label: "Grid view", defaultBindings: ["v g"] },
  { id: "list.view.list", group: "List Pages", label: "List view", defaultBindings: ["v l"] },
  { id: "list.view.wall", group: "List Pages", label: "Wall view", defaultBindings: ["v w"] },
  { id: "list.view.tagger", group: "List Pages", label: "Tagger view", defaultBindings: ["v t"] },
  { id: "list.view.graph", group: "List Pages", label: "Graph view", defaultBindings: ["v h"] },
  { id: "list.view.group", group: "List Pages", label: "Group view", defaultBindings: ["v b"] },
  { id: "list.view.feed", group: "List Pages", label: "Feed view", defaultBindings: ["v f"] },
  { id: "list.view.vertical", group: "List Pages", label: "Vertical view", defaultBindings: ["v k"] },
  { id: "list.select.all", group: "List Pages", label: "Select all", defaultBindings: ["s a"] },
  { id: "list.select.none", group: "List Pages", label: "Select none", defaultBindings: ["s n"] },
  { id: "list.select.invert", group: "List Pages", label: "Invert selection", defaultBindings: ["s i"] },
  { id: "list.page.previous", group: "List Pages", label: "Previous page", defaultBindings: ["ArrowLeft"], repeatable: true },
  { id: "list.page.next", group: "List Pages", label: "Next page", defaultBindings: ["ArrowRight"], repeatable: true },
  { id: "list.page.back10", group: "List Pages", label: "Back 10 pages", defaultBindings: ["Shift+ArrowLeft"], repeatable: true },
  { id: "list.page.forward10", group: "List Pages", label: "Forward 10 pages", defaultBindings: ["Shift+ArrowRight"], repeatable: true },
  { id: "list.page.first", group: "List Pages", label: "First page", defaultBindings: ["Mod+Home"] },
  { id: "list.page.last", group: "List Pages", label: "Last page", defaultBindings: ["Mod+End"] },
  { id: "list.filters", group: "List Pages", label: "Filters", defaultBindings: ["f"] },
  { id: "list.zoom.in", group: "List Pages", label: "Zoom in", defaultBindings: ["+"], repeatable: true },
  { id: "list.zoom.out", group: "List Pages", label: "Zoom out", defaultBindings: ["-"], repeatable: true },
  { id: "detail.edit", group: "Detail Pages", label: "Edit", defaultBindings: ["e"] },
  { id: "detail.favorite", group: "Detail Pages", label: "Toggle favorite", defaultBindings: ["o"] },
  { id: "detail.performer.videos", group: "Performer Detail", label: "Open videos", defaultBindings: ["c"] },
  { id: "detail.performer.galleries", group: "Performer Detail", label: "Open galleries", defaultBindings: ["g"] },
  { id: "detail.gallery.images", group: "Gallery Detail", label: "Open images", defaultBindings: ["a"] },
  { id: "detail.gallery.videos", group: "Gallery Detail", label: "Open videos", defaultBindings: ["s"] },
  { id: "detail.fileInfo", group: "Detail Pages", label: "Open file information", defaultBindings: ["i"] },
  { id: "detail.video.details", group: "Video Detail", label: "Open details", defaultBindings: ["a"] },
  { id: "detail.video.segments", group: "Video Detail", label: "Open segments", defaultBindings: ["s"] },
  { id: "detail.video.history", group: "Video Detail", label: "Open history", defaultBindings: ["h"] },
  { id: "detail.previous", group: "Detail Pages", label: "Open previous item", defaultBindings: ["["] },
  { id: "detail.next", group: "Detail Pages", label: "Open next item", defaultBindings: ["]"] },
  { id: "detail.image.likes", group: "Image Detail", label: "Add like", defaultBindings: ["l"] },
  { id: "detail.image.lightbox", group: "Image Detail", label: "Toggle lightbox", defaultBindings: ["f"] },
  { id: "detail.image.detections", group: "Image Detail", label: "Open detections", defaultBindings: ["d"] },
  { id: "detail.segment.parent", group: "Segment Detail", label: "Open parent video", defaultBindings: ["s"] },
  { id: "player.playPause", group: "Video Player", label: "Play or pause", defaultBindings: ["Space", "k"] },
  { id: "player.seekBackward", group: "Video Player", label: "Seek backward", defaultBindings: ["ArrowLeft"], repeatable: true },
  { id: "player.seekForward", group: "Video Player", label: "Seek forward", defaultBindings: ["ArrowRight"], repeatable: true },
  { id: "player.seekBackwardLarge", group: "Video Player", label: "Seek backward 10 seconds", defaultBindings: ["Shift+ArrowLeft"], repeatable: true },
  { id: "player.seekForwardLarge", group: "Video Player", label: "Seek forward 10 seconds", defaultBindings: ["Shift+ArrowRight"], repeatable: true },
  { id: "player.volumeUp", group: "Video Player", label: "Increase volume", defaultBindings: ["ArrowUp"], repeatable: true },
  { id: "player.volumeDown", group: "Video Player", label: "Decrease volume", defaultBindings: ["ArrowDown"], repeatable: true },
  { id: "player.mute", group: "Video Player", label: "Toggle mute", defaultBindings: ["m"] },
  { id: "player.fullscreen", group: "Video Player", label: "Toggle fullscreen", defaultBindings: ["f"] },
  ...Array.from({ length: 10 }, (_, value): KeyboardActionDefinition => ({
    id: `player.seekPercent.${value}`,
    group: "Video Player",
    label: `Seek to ${value * 10}%`,
    defaultBindings: [String(value)],
  })),
  { id: "viewer.previous", group: "Image Viewer", label: "Previous image", defaultBindings: ["ArrowLeft"], repeatable: true },
  { id: "viewer.next", group: "Image Viewer", label: "Next image", defaultBindings: ["ArrowRight"], repeatable: true },
  { id: "viewer.slideshow", group: "Image Viewer", label: "Toggle slideshow", defaultBindings: ["Space"] },
  { id: "viewer.fullscreen", group: "Image Viewer", label: "Toggle fullscreen", defaultBindings: ["f"] },
];

const stashBindings: Record<string, string[]> = {
  "global.shortcuts": [],
  "global.help": ["?"],
  "detail.favorite": ["o"],
  "detail.fileInfo": ["i"],
  "detail.image.likes": ["o"],
  "detail.image.lightbox": [],
  "player.playPause": ["Space", "Enter"],
};

const stashSupported = new Set([
  "global.help", "global.videos", "global.images", "global.groups", "global.galleries", "global.performers",
  "global.studios", "global.tags", "global.settings", "list.search", "list.view.grid", "list.view.list", "list.view.wall",
  "list.view.tagger", "list.select.all", "list.select.none", "list.select.invert", "list.page.previous", "list.page.next",
  "list.page.back10", "list.page.forward10", "list.page.first", "list.page.last", "list.filters", "list.zoom.in",
  "list.zoom.out", "detail.edit", "detail.favorite", "detail.performer.videos", "detail.performer.galleries",
  "detail.gallery.images", "detail.fileInfo", "detail.video.details", "detail.video.segments", "detail.video.history",
  "detail.image.likes", "player.playPause", "player.seekBackward", "player.seekForward", "player.volumeUp",
  "player.volumeDown", "player.mute", "player.fullscreen", "viewer.previous", "viewer.next",
]);

export const BUILTIN_KEYBOARD_PRESETS: KeyboardShortcutPreset[] = [
  {
    schemaVersion: 1,
    id: COVE_KEYBOARD_PRESET_ID,
    name: "Cove Native",
    description: "Cove's native keyboard shortcuts.",
    version: "1",
    unmappedActions: "action-defaults",
    bindings: {},
    provenance: { source: "cove" },
  },
  {
    schemaVersion: 1,
    id: STASH_KEYBOARD_PRESET_ID,
    name: "Stash v0.31.1",
    description: "Keyboard mappings compatible with equivalent Stash actions.",
    version: "0.31.1",
    unmappedActions: "unbound",
    bindings: Object.fromEntries(COVE_KEYBOARD_ACTIONS.map((action) => [
      action.id,
      stashBindings[action.id] ?? (stashSupported.has(action.id) ? action.defaultBindings : []),
    ])),
    provenance: { source: "cove", originalPresetId: "stashapp/stash@v0.31.1" },
  },
  {
    schemaVersion: 1,
    id: DISABLED_KEYBOARD_PRESET_ID,
    name: "Disabled",
    description: "Disable configurable semantic keyboard shortcuts.",
    version: "1",
    unmappedActions: "unbound",
    bindings: {},
    provenance: { source: "cove" },
  },
];
