import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import { useAuth } from "../auth/AuthContext";
import { useAppConfig } from "../state/AppConfigContext";
import { useExtensions } from "../extensions/ExtensionLoader";
import { updateAuthenticatedUserUiPreferences } from "../utils/userUiPreferences";
import { isOverlayOpen } from "../utils/overlayState";
import { normalizeShortcutEvent, normalizeShortcutSequence } from "./keybindings";
import {
  BUILTIN_KEYBOARD_PRESETS,
  COVE_KEYBOARD_ACTIONS,
  COVE_KEYBOARD_PRESET_ID,
} from "./catalog";
import {
  flattenKeyboardPreset,
  getKeyboardSequenceContinuations,
  resolveKeyboardDispatch,
  resolveKeyboardPreset,
  validateKeyboardPreset,
  type KeyboardActionDefinition,
  type KeyboardShortcutPreset,
  type KeyboardShortcutSurface,
} from "./registry";

const STORAGE_KEY = "cove-keyboard-shortcut-preferences-v1";
const LEGACY_PRESET_ID = "user:legacy-cove-shortcuts";
const SEQUENCE_TIMEOUT_MS = 800;

const SURFACE_PRIORITY: Record<KeyboardShortcutSurface, number> = {
  global: 0,
  page: 10,
  detail: 20,
  list: 30,
  player: 30,
  local: 40,
  viewer: 50,
  overlay: 60,
};

function hasDocumentKeyboardOverlay(target: EventTarget | null) {
  return isOverlayOpen() || document.querySelector(
    "[role='dialog'], [aria-modal='true']",
  ) != null || (target instanceof Element && target.closest("[role='listbox'], [role='menu']") != null);
}

/** Host-owned dispatch context supplied after Cove resolves and claims a shortcut. */
export interface KeyboardActionInvocation {
  /** The normalized one- or multi-stroke sequence that resolved this action. */
  sequence: string;
  /** The target of the final keyboard stroke, useful for restoring focus after an action. */
  target: EventTarget | null;
  /** Whether the final keyboard stroke was generated by key repeat. */
  repeat: boolean;
}

export interface KeyboardActionRegistration {
  id: string;
  action: (context: KeyboardActionInvocation) => void;
  enabled?: boolean;
  surface?: KeyboardShortcutSurface;
  bindings?: string[];
}

interface ActiveRegistration extends KeyboardActionRegistration {
  token: symbol;
  order: number;
}

export interface KeyboardShortcutState {
  actions: KeyboardActionDefinition[];
  presets: KeyboardShortcutPreset[];
  activePresetId: string;
  effectivePresetId: string;
  effectiveBindings: Record<string, string[]>;
  activeActionIds: Set<string>;
  shortcutDialogOpen: boolean;
  dispatchSuspended: boolean;
  setDispatchSuspended(suspended: boolean): void;
  showChordHints: boolean;
  setShowChordHints(show: boolean): void;
  setShortcutDialogOpen(open: boolean): void;
  selectPreset(id: string): void;
  clonePreset(id: string, name?: string): KeyboardShortcutPreset | null;
  updatePersonalPreset(preset: KeyboardShortcutPreset): void;
  deletePersonalPreset(id: string): void;
  importPreset(raw: string): KeyboardShortcutPreset;
  exportPreset(id: string): string | null;
  register(registrations: KeyboardActionRegistration[]): () => void;
}

const KeyboardShortcutContext = createContext<KeyboardShortcutState | null>(null);
let registrationOrder = 0;

function readStoredPreferences() {
  if (typeof window === "undefined") return null;
  try {
    return JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "null") as {
      activePresetId?: string;
      personalPresets?: KeyboardShortcutPreset[];
      showChordHints?: boolean;
    } | null;
  } catch {
    return null;
  }
}

function createPersonalPresetId() {
  return `user:${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
}

function normalizePersonalPresets(values: KeyboardShortcutPreset[] | null | undefined) {
  return (values ?? []).filter((preset) => validateKeyboardPreset(preset).valid);
}

export function keepResolvableKeyboardPresets(
  candidates: KeyboardShortcutPreset[],
  actions: KeyboardActionDefinition[],
) {
  return candidates.filter((preset) => {
    try {
      resolveKeyboardPreset(preset, candidates, actions);
      return true;
    } catch {
      return false;
    }
  });
}

export function KeyboardShortcutProvider({ children }: { children: ReactNode }) {
  const { user, hasPermission } = useAuth();
  const { config } = useAppConfig();
  const { manifest } = useExtensions();
  const stored = useMemo(readStoredPreferences, []);
  const serverPreferences = user?.uiPreferences?.keyboardShortcuts;
  const legacyOverrides = user?.uiPreferences?.keybindingOverrides ?? config?.ui.keybindingOverrides;
  const hasLegacyOverrides = !!legacyOverrides && Object.keys(legacyOverrides).length > 0;
  const [activePresetId, setActivePresetId] = useState(
    () => serverPreferences?.activePresetId ?? stored?.activePresetId ?? (hasLegacyOverrides ? LEGACY_PRESET_ID : COVE_KEYBOARD_PRESET_ID),
  );
  const [personalPresets, setPersonalPresets] = useState<KeyboardShortcutPreset[]>(() => {
    const serverPresets = normalizePersonalPresets(serverPreferences?.personalPresets as KeyboardShortcutPreset[] | undefined);
    const explicit = serverPresets.length > 0 ? serverPresets : normalizePersonalPresets(stored?.personalPresets);
    if (explicit.length > 0 || !legacyOverrides || Object.keys(legacyOverrides).length === 0) return explicit;
    return [{
      schemaVersion: 1,
      id: LEGACY_PRESET_ID,
      name: "My Cove shortcuts",
      basePresetId: COVE_KEYBOARD_PRESET_ID,
      unmappedActions: "unbound",
      bindings: Object.fromEntries(Object.entries(legacyOverrides).map(([id, value]) => [id, [value]])),
      provenance: { source: "personal", originalPresetId: COVE_KEYBOARD_PRESET_ID },
    }];
  });
  const [shortcutDialogOpen, setShortcutDialogOpen] = useState(false);
  const [showChordHints, setShowChordHintsState] = useState(
    () => serverPreferences?.showChordHints ?? stored?.showChordHints ?? true,
  );
  const [dispatchSuspended, setDispatchSuspended] = useState(false);
  const [conflictMessage, setConflictMessage] = useState<string | null>(null);
  const [pendingSequence, setPendingSequence] = useState<{ sequence: string; continuations: string[] } | null>(null);
  const registrationsRef = useRef<ActiveRegistration[]>([]);
  const [registrationRevision, setRegistrationRevision] = useState(0);
  const sequenceBufferRef = useRef<string[]>([]);
  const sequenceTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const extensionActions = useMemo<KeyboardActionDefinition[]>(() => (manifest?.keyboardActions ?? [])
    .filter((action) => !action.requiredPermission || hasPermission(action.requiredPermission))
    .map((action) => ({
      id: action.id,
      label: action.label,
      description: action.description,
      group: action.group || `Extension: ${action.extensionId}`,
      defaultBindings: action.defaultBindings ?? [],
      scopes: action.scopes,
      source: "extension",
      extensionId: action.extensionId,
      repeatable: action.repeatable,
      allowInEditable: action.allowInEditable,
      requiredPermission: action.requiredPermission,
    })), [hasPermission, manifest?.keyboardActions]);
  const actions = useMemo(() => [...COVE_KEYBOARD_ACTIONS, ...extensionActions], [extensionActions]);
  const extensionPresets = useMemo<KeyboardShortcutPreset[]>(() => (manifest?.keyboardShortcutPresets ?? [])
    .map((preset) => ({
      ...preset,
      provenance: { source: "extension" as const, providerId: preset.extensionId },
    }))
    .filter((preset) => validateKeyboardPreset(preset).valid), [manifest?.keyboardShortcutPresets]);
  const presets = useMemo(() => keepResolvableKeyboardPresets(
    [...BUILTIN_KEYBOARD_PRESETS, ...extensionPresets, ...personalPresets],
    actions,
  ), [actions, extensionPresets, personalPresets]);
  const selectedPreset = presets.find((preset) => preset.id === activePresetId);
  const fallbackPreset = presets.find((preset) => preset.id === COVE_KEYBOARD_PRESET_ID)!;
  const effectivePreset = selectedPreset ?? fallbackPreset;
  const effectiveBindings = useMemo(
    () => resolveKeyboardPreset(effectivePreset, presets, actions).bindings,
    [actions, effectivePreset, presets],
  );

  const persist = useCallback((nextActivePresetId: string, nextPersonalPresets: KeyboardShortcutPreset[], nextShowChordHints = showChordHints) => {
    const value = { activePresetId: nextActivePresetId, personalPresets: nextPersonalPresets, showChordHints: nextShowChordHints };
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
    } catch {
      // Server-backed preferences remain authoritative when browser storage is unavailable or full.
    }
    updateAuthenticatedUserUiPreferences((current) => ({
      ...(current ?? {}),
      keyboardShortcuts: value,
    }));
  }, [showChordHints]);

  const setShowChordHints = useCallback((show: boolean) => {
    setShowChordHintsState(show);
    persist(activePresetId, personalPresets, show);
  }, [activePresetId, persist, personalPresets]);

  const selectPreset = useCallback((id: string) => {
    setActivePresetId(id);
    persist(id, personalPresets);
  }, [persist, personalPresets]);

  const updatePersonalPreset = useCallback((preset: KeyboardShortcutPreset) => {
    if (preset.provenance?.source !== "personal" && preset.provenance?.source !== "import") return;
    if (!validateKeyboardPreset(preset).valid) return;
    setPersonalPresets((current) => {
      const next = current.some((entry) => entry.id === preset.id)
        ? current.map((entry) => entry.id === preset.id ? preset : entry)
        : [...current, preset];
      persist(activePresetId, next);
      return next;
    });
  }, [activePresetId, persist]);

  const clonePreset = useCallback((id: string, name?: string) => {
    const source = presets.find((preset) => preset.id === id);
    if (!source) return null;
    const clone = flattenKeyboardPreset(source, presets, actions, {
      id: createPersonalPresetId(),
      name: name?.trim() || `${source.name} copy`,
    });
    const next = [...personalPresets, clone];
    setPersonalPresets(next);
    setActivePresetId(clone.id);
    persist(clone.id, next);
    return clone;
  }, [actions, persist, personalPresets, presets]);

  const deletePersonalPreset = useCallback((id: string) => {
    const next = personalPresets.filter((preset) => preset.id !== id);
    const nextActive = activePresetId === id ? COVE_KEYBOARD_PRESET_ID : activePresetId;
    setPersonalPresets(next);
    setActivePresetId(nextActive);
    persist(nextActive, next);
  }, [activePresetId, persist, personalPresets]);

  const importPreset = useCallback((raw: string) => {
    if (new Blob([raw]).size > 1024 * 1024) throw new Error("Keyboard preset files may not exceed 1 MiB.");
    const parsed = JSON.parse(raw) as KeyboardShortcutPreset;
    const validation = validateKeyboardPreset(parsed);
    if (!validation.valid) throw new Error(validation.errors.join(" "));
    const imported = flattenKeyboardPreset(parsed, [...presets, parsed], actions, {
      id: createPersonalPresetId(),
      name: parsed.name,
    });
    imported.provenance = {
      source: "import",
      providerId: parsed.provenance?.providerId,
      originalPresetId: parsed.id,
    };
    const next = [...personalPresets, imported];
    setPersonalPresets(next);
    setActivePresetId(imported.id);
    persist(imported.id, next);
    return imported;
  }, [actions, persist, personalPresets, presets]);

  const exportPreset = useCallback((id: string) => {
    const source = presets.find((preset) => preset.id === id);
    if (!source) return null;
    const flattened = flattenKeyboardPreset(source, presets, actions, {
      id: source.id,
      name: source.name,
    });
    flattened.provenance = source.provenance;
    return `${JSON.stringify(flattened, null, 2)}\n`;
  }, [actions, presets]);

  const register = useCallback((values: KeyboardActionRegistration[]) => {
    const entries = values.map((value): ActiveRegistration => ({
      ...value,
      token: Symbol(value.id),
      order: ++registrationOrder,
    }));
    registrationsRef.current = [...registrationsRef.current, ...entries];
    setRegistrationRevision((revision) => revision + 1);
    return () => {
      const tokens = new Set(entries.map((entry) => entry.token));
      registrationsRef.current = registrationsRef.current.filter((entry) => !tokens.has(entry.token));
      setRegistrationRevision((revision) => revision + 1);
    };
  }, []);

  const actionById = useMemo(() => new Map(actions.map((action) => [action.id, action])), [actions]);
  const activeActionIds = useMemo(
    () => new Set(registrationsRef.current.filter((entry) => entry.enabled !== false).map((entry) => entry.id)),
    // registrationRevision intentionally turns the ref into reactive state.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [registrationRevision],
  );

  useEffect(() => {
    const clearBuffer = () => {
      sequenceBufferRef.current = [];
      setPendingSequence(null);
      if (sequenceTimerRef.current) clearTimeout(sequenceTimerRef.current);
      sequenceTimerRef.current = null;
    };
    const handler = (event: KeyboardEvent) => {
      if (dispatchSuspended) return;
      const stroke = normalizeShortcutEvent(event);
      if (!stroke) return;
      if (stroke === "Escape" && sequenceBufferRef.current.length > 0) {
        event.preventDefault();
        event.stopImmediatePropagation();
        clearBuffer();
        return;
      }
      const target = event.target as HTMLElement | null;
      const editable = target?.isContentEditable || ["INPUT", "TEXTAREA", "SELECT"].includes(target?.tagName ?? "");
      const candidates = registrationsRef.current.flatMap((registration) => {
        if (registration.enabled === false) return [];
        const definition = actionById.get(registration.id);
        if (!definition && !registration.id.startsWith("legacy:")) return [];
        if (editable && !definition?.allowInEditable) return [];
        if (event.repeat && definition && !definition.repeatable) return [];
        if (registration.surface && definition
          && (definition.source === "extension" || definition.scopes?.length)
          && !definition.scopes?.some((scope) => scope.surface === registration.surface)) return [];
        const surface = registration.surface ?? definition?.scopes?.[0]?.surface ?? "page";
        if (hasDocumentKeyboardOverlay(event.target) && SURFACE_PRIORITY[surface] < SURFACE_PRIORITY.viewer) return [];
        const alternatives = registration.bindings ?? effectiveBindings[registration.id] ?? definition?.defaultBindings ?? [];
        return alternatives.map((keys) => ({
          registration,
          normalized: normalizeShortcutSequence(keys),
          priority: SURFACE_PRIORITY[surface],
        })).filter((candidate) => candidate.normalized);
      });

      sequenceBufferRef.current.push(stroke);
      const sequence = sequenceBufferRef.current.join(" ");
      const resolution = resolveKeyboardDispatch(candidates.map((candidate) => ({
        actionId: candidate.registration.id,
        sequence: candidate.normalized,
        priority: candidate.priority,
        value: candidate,
      })), sequence);
      if (resolution.kind === "action" || resolution.kind === "conflict") {
        event.preventDefault();
        event.stopImmediatePropagation();
        if (resolution.kind === "action") {
          resolution.candidate.value.registration.action({
            sequence,
            target: event.target,
            repeat: event.repeat,
          });
        } else {
          setConflictMessage(`Shortcut ${sequence} is assigned to multiple actions in this view.`);
          window.dispatchEvent(new CustomEvent("cove:keyboard-shortcut-conflict", {
            detail: { sequence, actionIds: resolution.actionIds },
          }));
        }
        clearBuffer();
        return;
      }

      if (resolution.kind === "prefix") {
        event.preventDefault();
        if (sequenceTimerRef.current) clearTimeout(sequenceTimerRef.current);
        setPendingSequence({
          sequence,
          continuations: getKeyboardSequenceContinuations(
            candidates.map((candidate) => ({
              actionId: candidate.registration.id,
              sequence: candidate.normalized,
              priority: candidate.priority,
              value: candidate,
            })),
            sequence,
          ),
        });
        sequenceTimerRef.current = setTimeout(clearBuffer, SEQUENCE_TIMEOUT_MS);
      } else {
        clearBuffer();
      }
    };
    window.addEventListener("keydown", handler, { capture: true });
    return () => {
      window.removeEventListener("keydown", handler, { capture: true });
      clearBuffer();
    };
  }, [actionById, dispatchSuspended, effectiveBindings]);

  const value = useMemo<KeyboardShortcutState>(() => ({
    actions,
    presets,
    activePresetId,
    effectivePresetId: effectivePreset.id,
    effectiveBindings,
    activeActionIds,
    shortcutDialogOpen,
    dispatchSuspended,
    setDispatchSuspended,
    showChordHints,
    setShowChordHints,
    setShortcutDialogOpen,
    selectPreset,
    clonePreset,
    updatePersonalPreset,
    deletePersonalPreset,
    importPreset,
    exportPreset,
    register,
  }), [
    actions, activeActionIds, activePresetId, clonePreset, deletePersonalPreset, effectiveBindings, effectivePreset.id,
    dispatchSuspended, exportPreset, importPreset, presets, register, selectPreset, shortcutDialogOpen, showChordHints,
    setShowChordHints, updatePersonalPreset,
  ]);

  return (
    <KeyboardShortcutContext.Provider value={value}>
      {children}
      {conflictMessage && (
        <button
          type="button"
          onClick={() => setConflictMessage(null)}
          className="fixed bottom-5 right-5 z-[110] max-w-sm rounded-lg border border-amber-400/40 bg-card px-4 py-3 text-left text-sm text-foreground shadow-xl"
          role="alert"
        >
          {conflictMessage} Open Settings → Keyboard shortcuts to resolve it.
        </button>
      )}
      {showChordHints && pendingSequence && (
        <div
          className="pointer-events-none fixed bottom-5 left-1/2 z-[109] -translate-x-1/2 rounded-xl border border-border bg-card/95 px-4 py-3 text-center shadow-xl backdrop-blur"
          role="status"
          aria-live="polite"
        >
          <div className="font-mono text-sm font-semibold text-foreground">{pendingSequence.sequence} …</div>
          <div className="mt-1 text-xs text-secondary">
            Next: {pendingSequence.continuations.join(" · ")} · Esc to cancel
          </div>
        </div>
      )}
    </KeyboardShortcutContext.Provider>
  );
}

export function useKeyboardShortcuts() {
  const context = useContext(KeyboardShortcutContext);
  if (!context) throw new Error("useKeyboardShortcuts must be used within KeyboardShortcutProvider.");
  return context;
}

export function useOptionalKeyboardShortcuts() {
  return useContext(KeyboardShortcutContext);
}

export function useRegisterKeyboardActions(registrations: KeyboardActionRegistration[]) {
  const context = useOptionalKeyboardShortcuts();
  const register = context?.register;
  const registrationKey = registrations.map((entry) => [
    entry.id,
    entry.enabled !== false,
    entry.surface ?? "page",
    entry.bindings?.join("\u001f") ?? "",
  ].join("\u001e")).join("\u001d");
  const registrationsRef = useRef(registrations);
  registrationsRef.current = registrations;

  useEffect(() => {
    if (!register) return;
    return register(registrationsRef.current.map((entry, index) => ({
      ...entry,
      action: (event) => registrationsRef.current[index]?.action(event),
    })));
  }, [register, registrationKey]);
}
