namespace Cove.ApiTests.Infrastructure;

public sealed record EndpointCoverageException(ApiEndpointId Endpoint, string Reason);

public static class EndpointCoverageProgress
{
    public const int ExpectedMappedEndpoints = 93;

    public const int ExpectedTemporarilyUnmappedEndpoints = 407;

    public static IReadOnlySet<ApiEndpointId> TemporarilyUnmapped { get; } =
        TemporaryUnmappedEndpointText
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(ApiEndpointId.Parse)
            .ToHashSet();

    public static IReadOnlyList<EndpointCoverageException> Exceptions { get; } = [];

    private const string TemporaryUnmappedEndpointText = """
        DELETE /api/apitokens/{id:guid}
        DELETE /api/audios/bulk
        DELETE /api/audios/{id:int}
        DELETE /api/audios/{id:int}/image
        DELETE /api/audios/{id:int}/like
        DELETE /api/audios/{id:int}/like/history
        DELETE /api/auth/external/links/{linkid:int}
        DELETE /api/content-rules/overrides/{id:int}
        DELETE /api/content-rules/{id:int}
        DELETE /api/custom-fields/{id:int}
        DELETE /api/embeddings
        DELETE /api/faces/{id:int}/image
        DELETE /api/galleries/bulk
        DELETE /api/galleries/{galleryid:int}/chapters/{chapterid:int}
        DELETE /api/galleries/{id:int}
        DELETE /api/galleries/{id:int}/cover
        DELETE /api/galleries/{id:int}/image
        DELETE /api/galleries/{id:int}/image/back
        DELETE /api/galleries/{id:int}/images
        DELETE /api/groups/bulk
        DELETE /api/groups/{groupid:int}/items/{id:int}
        DELETE /api/groups/{id:int}
        DELETE /api/groups/{id:int}/image/back
        DELETE /api/groups/{id:int}/image/front
        DELETE /api/groups/{id:int}/subgroups/{subgroupid:int}
        DELETE /api/images/bulk
        DELETE /api/images/{id:int}
        DELETE /api/images/{id:int}/like
        DELETE /api/images/{id:int}/like/history
        DELETE /api/images/{imageid:int}/detections/{id:int}
        DELETE /api/jobs/{jobid}
        DELETE /api/performers/bulk
        DELETE /api/performers/{id:int}
        DELETE /api/performers/{id:int}/image
        DELETE /api/roles/{id:int}
        DELETE /api/savedfilters/{id:int}
        DELETE /api/segment-display-profiles/{id:int}
        DELETE /api/segment-display-profiles/{profileid:int}/rules/{id:int}
        DELETE /api/segments/{id:int}/image
        DELETE /api/share-links/{id:guid}
        DELETE /api/studios/bulk
        DELETE /api/studios/{id:int}
        DELETE /api/studios/{id:int}/image
        DELETE /api/tagapplications/host/{hosttype}/{hostid:int}/tag/{tagid:int}
        DELETE /api/tagapplications/{id:int}
        DELETE /api/tags/bulk
        DELETE /api/tags/{id:int}
        DELETE /api/tags/{id:int}/image
        DELETE /api/texts/bulk
        DELETE /api/texts/{id:int}
        DELETE /api/texts/{id:int}/image
        DELETE /api/texts/{id:int}/like
        DELETE /api/texts/{id:int}/like/history
        DELETE /api/users/{id:int}
        DELETE /api/users/{id:int}/external-links/{linkid:int}
        DELETE /api/videos/{id:int}
        DELETE /api/videos/{id:int}/image
        DELETE /api/videos/{id:int}/like
        DELETE /api/videos/{id:int}/like/history
        DELETE /api/videos/{id:int}/play
        DELETE /api/videos/{id:int}/rating
        DELETE /api/videos/{videoid:int}/detections/{id:int}
        DELETE /api/videos/{videoid:int}/segments/{id:int}
        GET /api/ai-runs/{id:int}
        GET /api/audios/{id:int}
        GET /api/audios/{id:int}/history
        GET /api/audios/{id:int}/image
        GET /api/audios/{id:int}/stream
        GET /api/auth/bootstrap-status
        GET /api/auth/external/links
        GET /api/auth/external/providers
        GET /api/auth/invite-info
        GET /api/content-rules/overrides
        GET /api/embeddings/{id:int}
        GET /api/engagement/interactions
        GET /api/extensions/assets/{extensionid}/{**path}
        GET /api/extensions/bundles/ui.css
        GET /api/extensions/bundles/ui.mjs
        GET /api/extensions/categories
        GET /api/extensions/dependencies/validate
        GET /api/extensions/manifest
        GET /api/extensions/registry/categories
        GET /api/extensions/registry/search
        GET /api/extensions/registry/updates
        GET /api/extensions/registry/{extensionid}
        GET /api/extensions/registry/{extensionid}/dependencies
        GET /api/extensions/{id}/data
        GET /api/extensions/{id}/dependencies/missing
        GET /api/faces/review/ai-run
        GET /api/faces/review/unlinked
        GET /api/faces/{id:int}/image
        GET /api/faces/{id:int}/similar
        GET /api/faces/{id:int}/suggestions
        GET /api/galleries/{id:int}
        GET /api/galleries/{id:int}/chapters
        GET /api/galleries/{id:int}/cover
        GET /api/galleries/{id:int}/image
        GET /api/galleries/{id:int}/image/back
        GET /api/groups/dynamic-sources
        GET /api/groups/{groupid:int}/items/page
        GET /api/groups/{groupid:int}/playback-manifest
        GET /api/groups/{id:int}
        GET /api/groups/{id:int}/containinggroups
        GET /api/groups/{id:int}/image/back
        GET /api/groups/{id:int}/image/front
        GET /api/groups/{id:int}/subgroups
        GET /api/images/{id:int}
        GET /api/images/{id:int}/history
        GET /api/images/{imageid:int}/detections/{id:int}
        GET /api/jobs/backup/latest
        GET /api/jobs/history
        GET /api/performers/{id:int}
        GET /api/performers/{id:int}/appears-with
        GET /api/performers/{id:int}/groups
        GET /api/performers/{id:int}/metadata-server/search
        GET /api/plugins/tasks
        GET /api/plugins/{pluginid}/config
        GET /api/roles/permissions
        GET /api/roles/{id:int}
        GET /api/savedfilters/{id:int}
        GET /api/scrape-attempts/{id:guid}
        GET /api/segment-display-profiles/{id:int}
        GET /api/segment-display-profiles/{profileid:int}/rules
        GET /api/segments/kinds/distinct
        GET /api/segments/source-keys/distinct
        GET /api/segments/{id:int}
        GET /api/segments/{id:int}/image
        GET /api/stash-migration/import/{jobid}
        GET /api/stream/detection/{detectionid:int}/crop
        GET /api/stream/image/{imageid:int}
        GET /api/stream/image/{imageid:int}/thumbnail
        GET /api/stream/video/{videoid:int}
        GET /api/stream/video/{videoid:int}/caption/{captionid:int}
        GET /api/stream/video/{videoid:int}/captions
        GET /api/stream/video/{videoid:int}/hls/master.m3u8
        GET /api/stream/video/{videoid:int}/hls/segment/{segment}
        GET /api/stream/video/{videoid:int}/hls/{profile}.m3u8
        GET /api/stream/video/{videoid:int}/preview
        GET /api/stream/video/{videoid:int}/resolutions
        GET /api/stream/video/{videoid:int}/screenshot
        GET /api/stream/video/{videoid:int}/segment-preview
        GET /api/stream/video/{videoid:int}/sprite
        GET /api/stream/video/{videoid:int}/transcode
        GET /api/stream/video/{videoid:int}/vtt/thumbs
        GET /api/studios/{id:int}
        GET /api/studios/{id:int}/image
        GET /api/studios/{id:int}/metadata-server/search
        GET /api/system/config
        GET /api/system/ffmpeg-capabilities
        GET /api/system/log-level
        GET /api/system/scrapers
        GET /api/system/stats
        GET /api/system/ui-assets/{filename}
        GET /api/tags/segment-titles
        GET /api/tags/{id:int}/image
        GET /api/tags/{id:int}/metadata-server/search
        GET /api/tags/{id:int}/segments
        GET /api/texts/{id:int}
        GET /api/texts/{id:int}/content
        GET /api/texts/{id:int}/history
        GET /api/texts/{id:int}/image
        GET /api/users/{id:int}
        GET /api/users/{id:int}/external-links
        GET /api/videos/duplicates
        GET /api/videos/wall
        GET /api/videos/with-compilations
        GET /api/videos/{id:int}
        GET /api/videos/{id:int}/image
        GET /api/videos/{id:int}/metadata-server/search
        GET /api/videos/{id:int}/ratings
        GET /api/videos/{videoid:int}/detections/{id:int}
        GET /api/videos/{videoid:int}/segments/spans
        GET /api/videos/{videoid:int}/segments/{id:int}
        GET /api/videos/{videoid:int}/spans/{spankey}
        HEAD /api/stream/video/{videoid:int}/preview
        PATCH /api/system/log-level
        POST /api/ai-data/purge
        POST /api/apitokens
        POST /api/audios
        POST /api/audios/aggregate
        POST /api/audios/bulk
        POST /api/audios/find
        POST /api/audios/from-file
        POST /api/audios/{id:int}/activity/reset
        POST /api/audios/{id:int}/image
        POST /api/audios/{id:int}/like
        POST /api/audios/{id:int}/like/historical
        POST /api/audios/{id:int}/like/reset
        POST /api/audios/{id:int}/rescan
        POST /api/auth/bootstrap-owner
        POST /api/auth/change-password
        POST /api/auth/external/links/cancel
        POST /api/auth/external/links/confirm
        POST /api/auth/external/links/preview
        POST /api/auth/external/redeem
        POST /api/auth/invite-redeem
        POST /api/auth/login
        POST /api/auth/logout
        POST /api/auth/refresh
        POST /api/auth/revoke-sessions
        POST /api/auth/setup-token-redeem
        POST /api/content-rules
        POST /api/content-rules/overrides
        POST /api/custom-fields
        POST /api/database/backup
        POST /api/database/config/backup
        POST /api/database/config/restore
        POST /api/database/migrate
        POST /api/database/optimize
        POST /api/database/restore
        POST /api/database/wipe
        POST /api/embeddings/search
        POST /api/engagement/activity/reset-all
        POST /api/engagement/batch
        POST /api/engagement/interactions
        POST /api/engagement/wipe-all
        POST /api/extensions/install-from-url
        POST /api/extensions/install-from-zip
        POST /api/extensions/registry/install
        POST /api/extensions/registry/uninstall
        POST /api/extensions/{id}/disable
        POST /api/extensions/{id}/enable
        POST /api/extensions/{id}/jobs/{jobid}/run
        POST /api/faces/batch/delete
        POST /api/faces/batch/link-top-suggestion
        POST /api/faces/{id:int}/image
        POST /api/faces/{id:int}/suggestions/decision
        POST /api/files/delete
        POST /api/files/fingerprints
        POST /api/files/folders/{id:int}/reveal
        POST /api/files/move
        POST /api/files/{id:int}/reveal
        POST /api/galleries
        POST /api/galleries/aggregate
        POST /api/galleries/bulk
        POST /api/galleries/find
        POST /api/galleries/{id:int}/chapters
        POST /api/galleries/{id:int}/image
        POST /api/galleries/{id:int}/image/back
        POST /api/galleries/{id:int}/images
        POST /api/galleries/{id:int}/rescan
        POST /api/groups
        POST /api/groups/bulk
        POST /api/groups/find
        POST /api/groups/{groupid:int}/items/from-spans
        POST /api/groups/{groupid:int}/items/remove-hosts
        POST /api/groups/{id:int}/image/back
        POST /api/groups/{id:int}/image/front
        POST /api/groups/{id:int}/snapshot
        POST /api/groups/{id:int}/subgroups
        POST /api/images
        POST /api/images/aggregate
        POST /api/images/bulk
        POST /api/images/find
        POST /api/images/{id:int}/like/historical
        POST /api/images/{id:int}/like/reset
        POST /api/images/{id:int}/rescan
        POST /api/jobs/backup
        POST /api/jobs/clean
        POST /api/jobs/generate-image-phashes
        POST /api/jobs/generate-thumbnails
        POST /api/jobs/generate-video-phashes
        POST /api/jobs/scan
        POST /api/metadata/export
        POST /api/metadata/identify
        POST /api/metadata/import
        POST /api/metadata/sync-fingerprints
        POST /api/performers
        POST /api/performers/bulk
        POST /api/performers/find
        POST /api/performers/merge
        POST /api/performers/metadata-server/batch-tag
        POST /api/performers/metadata-server/find-by-ids
        POST /api/performers/{id:int}/apply-scraped
        POST /api/performers/{id:int}/metadata-server/import
        POST /api/performers/{id:int}/metadata-server/submit-draft
        POST /api/performers/{id:int}/scrape
        POST /api/performers/{id:int}/scrape-preview
        POST /api/performers/{id:int}/scrape-url
        POST /api/plugins/reload
        POST /api/plugins/run-task
        POST /api/plugins/settings
        POST /api/plugins/{pluginid}/config
        POST /api/roles
        POST /api/savedfilters
        POST /api/scrape-attempts
        POST /api/scrape-attempts/resolve-relations
        POST /api/scrape-attempts/{id:guid}/apply
        POST /api/segment-display-profiles
        POST /api/segment-display-profiles/preview
        POST /api/segment-display-profiles/{profileid:int}/rules
        POST /api/segment-display-profiles/{profileid:int}/rules/bulk
        POST /api/segments/bulk/remove-tag
        POST /api/segments/spans/count
        POST /api/segments/spans/search
        POST /api/segments/{id:int}/image
        POST /api/segments/{id:int}/image/from-frame
        POST /api/share-links
        POST /api/stash-migration/import
        POST /api/studios
        POST /api/studios/bulk
        POST /api/studios/find
        POST /api/studios/merge
        POST /api/studios/metadata-server/batch-tag
        POST /api/studios/metadata-server/find-by-ids
        POST /api/studios/{id:int}/image
        POST /api/studios/{id:int}/metadata-server/import
        POST /api/studios/{id:int}/metadata-server/submit-draft
        POST /api/system/config/ui
        POST /api/system/maintenance/recompute-derived-counts
        POST /api/system/metadata-servers/validate
        POST /api/system/scrapers/match-url
        POST /api/system/scrapers/reload
        POST /api/system/scrapers/scrape-fragment
        POST /api/system/scrapers/scrape-name
        POST /api/system/scrapers/scrape-url
        POST /api/system/scrapers/scrape-url-auto
        POST /api/system/shutdown
        POST /api/system/ui/favicon
        POST /api/system/ui/logo
        POST /api/tagapplications
        POST /api/tags/bulk
        POST /api/tags/find
        POST /api/tags/graph
        POST /api/tags/metadata-server/batch-tag
        POST /api/tags/metadata-server/find-by-ids
        POST /api/tags/merge
        POST /api/tags/{id:int}/image
        POST /api/tags/{id:int}/metadata-server/import
        POST /api/tags/{id:int}/metadata-server/submit-draft
        POST /api/texts
        POST /api/texts/aggregate
        POST /api/texts/bulk
        POST /api/texts/find
        POST /api/texts/from-file
        POST /api/texts/{id:int}/image
        POST /api/texts/{id:int}/like
        POST /api/texts/{id:int}/like/historical
        POST /api/texts/{id:int}/like/reset
        POST /api/texts/{id:int}/rescan
        POST /api/users
        POST /api/users/invite
        POST /api/users/{id:int}/invite
        POST /api/users/{id:int}/password
        POST /api/users/{id:int}/roles
        POST /api/users/{id:int}/unlock
        POST /api/videos
        POST /api/videos/aggregate
        POST /api/videos/bulk
        POST /api/videos/destroy
        POST /api/videos/find
        POST /api/videos/from-file
        POST /api/videos/merge
        POST /api/videos/metadata-server/find-by-ids
        POST /api/videos/{id:int}/activity/reset
        POST /api/videos/{id:int}/assign-file
        POST /api/videos/{id:int}/cover/from-frame
        POST /api/videos/{id:int}/generate-screenshot
        POST /api/videos/{id:int}/image
        POST /api/videos/{id:int}/like/historical
        POST /api/videos/{id:int}/like/reset
        POST /api/videos/{id:int}/metadata-server/import
        POST /api/videos/{id:int}/metadata-server/submit-draft
        POST /api/videos/{id:int}/metadata-server/submit-fingerprints
        POST /api/videos/{id:int}/play
        POST /api/videos/{id:int}/play/reset
        POST /api/videos/{id:int}/rating
        POST /api/videos/{id:int}/rescan
        POST /api/videos/{videoid:int}/segments/spans/query
        PUT /api/audios/{id:int}
        PUT /api/auth/me/ui-preferences
        PUT /api/content-rules/{id:int}
        PUT /api/custom-fields
        PUT /api/custom-fields/{id:int}
        PUT /api/extensions/{id}/data/{key}
        PUT /api/galleries/{galleryid:int}/chapters/{chapterid:int}
        PUT /api/galleries/{id:int}
        PUT /api/galleries/{id:int}/cover
        PUT /api/galleries/{id:int}/image/back/source
        PUT /api/galleries/{id:int}/image/source
        PUT /api/groups/reorder
        PUT /api/groups/{groupid:int}/items/reorder
        PUT /api/groups/{groupid:int}/items/{id:int}
        PUT /api/groups/{id:int}
        PUT /api/groups/{id:int}/image/front/source
        PUT /api/groups/{id:int}/query
        PUT /api/groups/{id:int}/subgroups/reorder
        PUT /api/images/{id:int}
        PUT /api/images/{imageid:int}/detections/{id:int}
        PUT /api/jobs/{jobid}/reorder
        PUT /api/performers/{id:int}
        PUT /api/performers/{id:int}/image/source
        PUT /api/roles/{id:int}
        PUT /api/savedfilters/{id:int}
        PUT /api/segment-display-profiles/{id:int}
        PUT /api/segment-display-profiles/{id:int}/default
        PUT /api/segment-display-profiles/{profileid:int}/rules/{id:int}
        PUT /api/studios/{id:int}
        PUT /api/studios/{id:int}/image/source
        PUT /api/system/config
        PUT /api/system/config/ui/{key}
        PUT /api/tags/{id:int}/image/source
        PUT /api/texts/{id:int}
        PUT /api/users/{id:int}
        PUT /api/videos/{id:int}
        PUT /api/videos/{videoid:int}/detections/{id:int}
        PUT /api/videos/{videoid:int}/segments/{id:int}
        """;
}
