using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Cove.Data.Migrations;

[DbContext(typeof(CoveContext))]
[Migration("20260904043000_NormalizePerformerCountries")]
public sealed class NormalizePerformerCountries : Migration
{
    private static readonly (string Alias, string Code)[] Mappings =
    [
        ("AF", "AF"),
        ("Afghanistan", "AF"),
        ("AL", "AL"),
        ("Albania", "AL"),
        ("DZ", "DZ"),
        ("Algeria", "DZ"),
        ("AS", "AS"),
        ("American Samoa", "AS"),
        ("AD", "AD"),
        ("Andorra", "AD"),
        ("AO", "AO"),
        ("Angola", "AO"),
        ("AI", "AI"),
        ("Anguilla", "AI"),
        ("AQ", "AQ"),
        ("Antarctica", "AQ"),
        ("AG", "AG"),
        ("Antigua & Barbuda", "AG"),
        ("AR", "AR"),
        ("Argentina", "AR"),
        ("AM", "AM"),
        ("Armenia", "AM"),
        ("AW", "AW"),
        ("Aruba", "AW"),
        ("AU", "AU"),
        ("Australia", "AU"),
        ("AT", "AT"),
        ("Austria", "AT"),
        ("AZ", "AZ"),
        ("Azerbaijan", "AZ"),
        ("BS", "BS"),
        ("Bahamas", "BS"),
        ("BH", "BH"),
        ("Bahrain", "BH"),
        ("BD", "BD"),
        ("Bangladesh", "BD"),
        ("BB", "BB"),
        ("Barbados", "BB"),
        ("BY", "BY"),
        ("Belarus", "BY"),
        ("BE", "BE"),
        ("Belgium", "BE"),
        ("BZ", "BZ"),
        ("Belize", "BZ"),
        ("BJ", "BJ"),
        ("Benin", "BJ"),
        ("BM", "BM"),
        ("Bermuda", "BM"),
        ("BT", "BT"),
        ("Bhutan", "BT"),
        ("BO", "BO"),
        ("Bolivia", "BO"),
        ("BA", "BA"),
        ("Bosnia & Herzegovina", "BA"),
        ("BW", "BW"),
        ("Botswana", "BW"),
        ("BV", "BV"),
        ("Bouvet Island", "BV"),
        ("BR", "BR"),
        ("Brazil", "BR"),
        ("IO", "IO"),
        ("British Indian Ocean Territory", "IO"),
        ("VG", "VG"),
        ("British Virgin Islands", "VG"),
        ("BN", "BN"),
        ("Brunei", "BN"),
        ("BG", "BG"),
        ("Bulgaria", "BG"),
        ("BF", "BF"),
        ("Burkina Faso", "BF"),
        ("BI", "BI"),
        ("Burundi", "BI"),
        ("KH", "KH"),
        ("Cambodia", "KH"),
        ("CM", "CM"),
        ("Cameroon", "CM"),
        ("CA", "CA"),
        ("Canada", "CA"),
        ("CV", "CV"),
        ("Cape Verde", "CV"),
        ("BQ", "BQ"),
        ("Caribbean Netherlands", "BQ"),
        ("KY", "KY"),
        ("Cayman Islands", "KY"),
        ("CF", "CF"),
        ("Central African Republic", "CF"),
        ("TD", "TD"),
        ("Chad", "TD"),
        ("CL", "CL"),
        ("Chile", "CL"),
        ("CN", "CN"),
        ("China", "CN"),
        ("CX", "CX"),
        ("Christmas Island", "CX"),
        ("CC", "CC"),
        ("Cocos (Keeling) Islands", "CC"),
        ("CO", "CO"),
        ("Colombia", "CO"),
        ("KM", "KM"),
        ("Comoros", "KM"),
        ("CG", "CG"),
        ("Congo - Brazzaville", "CG"),
        ("CD", "CD"),
        ("Congo - Kinshasa", "CD"),
        ("CK", "CK"),
        ("Cook Islands", "CK"),
        ("CR", "CR"),
        ("Costa Rica", "CR"),
        ("HR", "HR"),
        ("Croatia", "HR"),
        ("CU", "CU"),
        ("Cuba", "CU"),
        ("CW", "CW"),
        ("Curaçao", "CW"),
        ("CY", "CY"),
        ("Cyprus", "CY"),
        ("CZ", "CZ"),
        ("Czechia", "CZ"),
        ("CI", "CI"),
        ("Côte d’Ivoire", "CI"),
        ("DK", "DK"),
        ("Denmark", "DK"),
        ("DJ", "DJ"),
        ("Djibouti", "DJ"),
        ("DM", "DM"),
        ("Dominica", "DM"),
        ("DO", "DO"),
        ("Dominican Republic", "DO"),
        ("EC", "EC"),
        ("Ecuador", "EC"),
        ("EG", "EG"),
        ("Egypt", "EG"),
        ("SV", "SV"),
        ("El Salvador", "SV"),
        ("GQ", "GQ"),
        ("Equatorial Guinea", "GQ"),
        ("ER", "ER"),
        ("Eritrea", "ER"),
        ("EE", "EE"),
        ("Estonia", "EE"),
        ("SZ", "SZ"),
        ("Eswatini", "SZ"),
        ("ET", "ET"),
        ("Ethiopia", "ET"),
        ("FK", "FK"),
        ("Falkland Islands", "FK"),
        ("FO", "FO"),
        ("Faroe Islands", "FO"),
        ("FJ", "FJ"),
        ("Fiji", "FJ"),
        ("FI", "FI"),
        ("Finland", "FI"),
        ("FR", "FR"),
        ("France", "FR"),
        ("GF", "GF"),
        ("French Guiana", "GF"),
        ("PF", "PF"),
        ("French Polynesia", "PF"),
        ("TF", "TF"),
        ("French Southern Territories", "TF"),
        ("GA", "GA"),
        ("Gabon", "GA"),
        ("GM", "GM"),
        ("Gambia", "GM"),
        ("GE", "GE"),
        ("Georgia", "GE"),
        ("DE", "DE"),
        ("Germany", "DE"),
        ("GH", "GH"),
        ("Ghana", "GH"),
        ("GI", "GI"),
        ("Gibraltar", "GI"),
        ("GR", "GR"),
        ("Greece", "GR"),
        ("GL", "GL"),
        ("Greenland", "GL"),
        ("GD", "GD"),
        ("Grenada", "GD"),
        ("GP", "GP"),
        ("Guadeloupe", "GP"),
        ("GU", "GU"),
        ("Guam", "GU"),
        ("GT", "GT"),
        ("Guatemala", "GT"),
        ("GG", "GG"),
        ("Guernsey", "GG"),
        ("GN", "GN"),
        ("Guinea", "GN"),
        ("GW", "GW"),
        ("Guinea-Bissau", "GW"),
        ("GY", "GY"),
        ("Guyana", "GY"),
        ("HT", "HT"),
        ("Haiti", "HT"),
        ("HM", "HM"),
        ("Heard Island and McDonald Islands", "HM"),
        ("HN", "HN"),
        ("Honduras", "HN"),
        ("HK", "HK"),
        ("Hong Kong SAR China", "HK"),
        ("HU", "HU"),
        ("Hungary", "HU"),
        ("IS", "IS"),
        ("Iceland", "IS"),
        ("IN", "IN"),
        ("India", "IN"),
        ("ID", "ID"),
        ("Indonesia", "ID"),
        ("IR", "IR"),
        ("Iran", "IR"),
        ("IQ", "IQ"),
        ("Iraq", "IQ"),
        ("IE", "IE"),
        ("Ireland", "IE"),
        ("IM", "IM"),
        ("Isle of Man", "IM"),
        ("IL", "IL"),
        ("Israel", "IL"),
        ("IT", "IT"),
        ("Italy", "IT"),
        ("JM", "JM"),
        ("Jamaica", "JM"),
        ("JP", "JP"),
        ("Japan", "JP"),
        ("JE", "JE"),
        ("Jersey", "JE"),
        ("JO", "JO"),
        ("Jordan", "JO"),
        ("KZ", "KZ"),
        ("Kazakhstan", "KZ"),
        ("KE", "KE"),
        ("Kenya", "KE"),
        ("KI", "KI"),
        ("Kiribati", "KI"),
        ("XK", "XK"),
        ("Kosovo", "XK"),
        ("KW", "KW"),
        ("Kuwait", "KW"),
        ("KG", "KG"),
        ("Kyrgyzstan", "KG"),
        ("LA", "LA"),
        ("Laos", "LA"),
        ("LV", "LV"),
        ("Latvia", "LV"),
        ("LB", "LB"),
        ("Lebanon", "LB"),
        ("LS", "LS"),
        ("Lesotho", "LS"),
        ("LR", "LR"),
        ("Liberia", "LR"),
        ("LY", "LY"),
        ("Libya", "LY"),
        ("LI", "LI"),
        ("Liechtenstein", "LI"),
        ("LT", "LT"),
        ("Lithuania", "LT"),
        ("LU", "LU"),
        ("Luxembourg", "LU"),
        ("MO", "MO"),
        ("Macao SAR China", "MO"),
        ("MG", "MG"),
        ("Madagascar", "MG"),
        ("MW", "MW"),
        ("Malawi", "MW"),
        ("MY", "MY"),
        ("Malaysia", "MY"),
        ("MV", "MV"),
        ("Maldives", "MV"),
        ("ML", "ML"),
        ("Mali", "ML"),
        ("MT", "MT"),
        ("Malta", "MT"),
        ("MH", "MH"),
        ("Marshall Islands", "MH"),
        ("MQ", "MQ"),
        ("Martinique", "MQ"),
        ("MR", "MR"),
        ("Mauritania", "MR"),
        ("MU", "MU"),
        ("Mauritius", "MU"),
        ("YT", "YT"),
        ("Mayotte", "YT"),
        ("MX", "MX"),
        ("Mexico", "MX"),
        ("FM", "FM"),
        ("Micronesia", "FM"),
        ("MD", "MD"),
        ("Moldova", "MD"),
        ("MC", "MC"),
        ("Monaco", "MC"),
        ("MN", "MN"),
        ("Mongolia", "MN"),
        ("ME", "ME"),
        ("Montenegro", "ME"),
        ("MS", "MS"),
        ("Montserrat", "MS"),
        ("MA", "MA"),
        ("Morocco", "MA"),
        ("MZ", "MZ"),
        ("Mozambique", "MZ"),
        ("MM", "MM"),
        ("Myanmar (Burma)", "MM"),
        ("NA", "NA"),
        ("Namibia", "NA"),
        ("NR", "NR"),
        ("Nauru", "NR"),
        ("NP", "NP"),
        ("Nepal", "NP"),
        ("NL", "NL"),
        ("Netherlands", "NL"),
        ("NC", "NC"),
        ("New Caledonia", "NC"),
        ("NZ", "NZ"),
        ("New Zealand", "NZ"),
        ("NI", "NI"),
        ("Nicaragua", "NI"),
        ("NE", "NE"),
        ("Niger", "NE"),
        ("NG", "NG"),
        ("Nigeria", "NG"),
        ("NU", "NU"),
        ("Niue", "NU"),
        ("NF", "NF"),
        ("Norfolk Island", "NF"),
        ("KP", "KP"),
        ("North Korea", "KP"),
        ("MK", "MK"),
        ("North Macedonia", "MK"),
        ("MP", "MP"),
        ("Northern Mariana Islands", "MP"),
        ("NO", "NO"),
        ("Norway", "NO"),
        ("OM", "OM"),
        ("Oman", "OM"),
        ("PK", "PK"),
        ("Pakistan", "PK"),
        ("PW", "PW"),
        ("Palau", "PW"),
        ("PS", "PS"),
        ("Palestinian Territories", "PS"),
        ("PA", "PA"),
        ("Panama", "PA"),
        ("PG", "PG"),
        ("Papua New Guinea", "PG"),
        ("PY", "PY"),
        ("Paraguay", "PY"),
        ("PE", "PE"),
        ("Peru", "PE"),
        ("PH", "PH"),
        ("Philippines", "PH"),
        ("PN", "PN"),
        ("Pitcairn Islands", "PN"),
        ("PL", "PL"),
        ("Poland", "PL"),
        ("PT", "PT"),
        ("Portugal", "PT"),
        ("PR", "PR"),
        ("Puerto Rico", "PR"),
        ("QA", "QA"),
        ("Qatar", "QA"),
        ("RO", "RO"),
        ("Romania", "RO"),
        ("RU", "RU"),
        ("Russia", "RU"),
        ("RW", "RW"),
        ("Rwanda", "RW"),
        ("RE", "RE"),
        ("Réunion", "RE"),
        ("WS", "WS"),
        ("Samoa", "WS"),
        ("SM", "SM"),
        ("San Marino", "SM"),
        ("SA", "SA"),
        ("Saudi Arabia", "SA"),
        ("SN", "SN"),
        ("Senegal", "SN"),
        ("RS", "RS"),
        ("Serbia", "RS"),
        ("SC", "SC"),
        ("Seychelles", "SC"),
        ("SL", "SL"),
        ("Sierra Leone", "SL"),
        ("SG", "SG"),
        ("Singapore", "SG"),
        ("SX", "SX"),
        ("Sint Maarten", "SX"),
        ("SK", "SK"),
        ("Slovakia", "SK"),
        ("SI", "SI"),
        ("Slovenia", "SI"),
        ("SB", "SB"),
        ("Solomon Islands", "SB"),
        ("SO", "SO"),
        ("Somalia", "SO"),
        ("ZA", "ZA"),
        ("South Africa", "ZA"),
        ("GS", "GS"),
        ("South Georgia and the South Sandwich Islands", "GS"),
        ("KR", "KR"),
        ("South Korea", "KR"),
        ("SS", "SS"),
        ("South Sudan", "SS"),
        ("ES", "ES"),
        ("Spain", "ES"),
        ("LK", "LK"),
        ("Sri Lanka", "LK"),
        ("BL", "BL"),
        ("St. Barthélemy", "BL"),
        ("SH", "SH"),
        ("St. Helena", "SH"),
        ("KN", "KN"),
        ("St. Kitts & Nevis", "KN"),
        ("LC", "LC"),
        ("St. Lucia", "LC"),
        ("MF", "MF"),
        ("St. Martin", "MF"),
        ("PM", "PM"),
        ("St. Pierre & Miquelon", "PM"),
        ("VC", "VC"),
        ("St. Vincent & Grenadines", "VC"),
        ("SD", "SD"),
        ("Sudan", "SD"),
        ("SR", "SR"),
        ("Suriname", "SR"),
        ("SJ", "SJ"),
        ("Svalbard & Jan Mayen", "SJ"),
        ("SE", "SE"),
        ("Sweden", "SE"),
        ("CH", "CH"),
        ("Switzerland", "CH"),
        ("SY", "SY"),
        ("Syria", "SY"),
        ("ST", "ST"),
        ("São Tomé & Príncipe", "ST"),
        ("TW", "TW"),
        ("Taiwan", "TW"),
        ("TJ", "TJ"),
        ("Tajikistan", "TJ"),
        ("TZ", "TZ"),
        ("Tanzania", "TZ"),
        ("TH", "TH"),
        ("Thailand", "TH"),
        ("TL", "TL"),
        ("Timor-Leste", "TL"),
        ("TG", "TG"),
        ("Togo", "TG"),
        ("TK", "TK"),
        ("Tokelau", "TK"),
        ("TO", "TO"),
        ("Tonga", "TO"),
        ("TT", "TT"),
        ("Trinidad & Tobago", "TT"),
        ("TN", "TN"),
        ("Tunisia", "TN"),
        ("TR", "TR"),
        ("Turkey", "TR"),
        ("TM", "TM"),
        ("Turkmenistan", "TM"),
        ("TC", "TC"),
        ("Turks & Caicos Islands", "TC"),
        ("TV", "TV"),
        ("Tuvalu", "TV"),
        ("UM", "UM"),
        ("U.S. Outlying Islands", "UM"),
        ("VI", "VI"),
        ("U.S. Virgin Islands", "VI"),
        ("UG", "UG"),
        ("Uganda", "UG"),
        ("UA", "UA"),
        ("Ukraine", "UA"),
        ("AE", "AE"),
        ("United Arab Emirates", "AE"),
        ("GB", "GB"),
        ("United Kingdom", "GB"),
        ("US", "US"),
        ("United States", "US"),
        ("UY", "UY"),
        ("Uruguay", "UY"),
        ("UZ", "UZ"),
        ("Uzbekistan", "UZ"),
        ("VU", "VU"),
        ("Vanuatu", "VU"),
        ("VA", "VA"),
        ("Vatican City", "VA"),
        ("VE", "VE"),
        ("Venezuela", "VE"),
        ("VN", "VN"),
        ("Vietnam", "VN"),
        ("WF", "WF"),
        ("Wallis & Futuna", "WF"),
        ("EH", "EH"),
        ("Western Sahara", "EH"),
        ("YE", "YE"),
        ("Yemen", "YE"),
        ("ZM", "ZM"),
        ("Zambia", "ZM"),
        ("ZW", "ZW"),
        ("Zimbabwe", "ZW"),
        ("AX", "AX"),
        ("Åland Islands", "AX"),
        ("Czech Republic", "CZ"),
        ("Great Britain", "GB"),
        ("Russian Federation", "RU"),
        ("Slovak Republic", "SK"),
        ("UK", "GB"),
        ("USA", "US"),
        ("United States of America", "US"),
    ];

    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("UPDATE performers SET \"Country\" = NULL WHERE btrim(\"Country\") = '';");
        migrationBuilder.Sql("UPDATE performers SET \"Country\" = btrim(\"Country\") WHERE \"Country\" IS NOT NULL;");

        var values = string.Join(", ", Mappings.Select(mapping =>
            $"('{Escape(mapping.Alias)}', '{Escape(mapping.Code)}')"));
        migrationBuilder.Sql(
            $"""
            UPDATE performers AS performer
            SET "Country" = mapping.code
            FROM (VALUES {values}) AS mapping(alias, code)
            WHERE lower(performer."Country") = lower(mapping.alias);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Canonical ISO codes cannot be losslessly converted back to the user's original spelling.
    }

    private static string Escape(string value) => value.Replace("'", "''", StringComparison.Ordinal);
}
