// <auto-generated />
using System;
using System.Collections.Generic;
using Cove.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cove.Data.Migrations
{
    [DbContext(typeof(CoveContext))]
    partial class CoveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cove.Core.Entities.BaseFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("ModTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ZipFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId", "Basename")
                        .IsUnique();

                    b.ToTable("files", (string)null);

                    b.HasDiscriminator<string>("FileType").HasValue("BaseFileEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cove.Core.Entities.ExtensionData", b =>
                {
                    b.Property<string>("ExtensionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExtensionId", "Key");

                    b.HasIndex("ExtensionId");

                    b.ToTable("extension_data", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.FileFingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("FileFingerprints");
                });

            modelBuilder.Entity("Cove.Core.Entities.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ZipFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("CoverImageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageBlobId")
                        .HasColumnType("text");

                    b.Property<bool>("Organized")
                        .HasColumnType("boolean");

                    b.Property<string>("Photographer")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("StudioId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("StudioId");

                    b.HasIndex("Title");

                    b.ToTable("galleries", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.Property<int>("ImageIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("gallery_chapters", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryPerformer", b =>
                {
                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.HasKey("GalleryId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.ToTable("gallery_performers", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryTag", b =>
                {
                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("GalleryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("gallery_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("GalleryUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aliases")
                        .HasColumnType("text");

                    b.Property<string>("BackImageBlobId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FrontImageBlobId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("StudioId")
                        .HasColumnType("integer");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("StudioId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupRelation", b =>
                {
                    b.Property<int>("ContainingGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("ContainingGroupId", "SubGroupId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("group_relations", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupTag", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("group_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int>("OCounter")
                        .HasColumnType("integer");

                    b.Property<bool>("Organized")
                        .HasColumnType("boolean");

                    b.Property<string>("Photographer")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("StudioId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Organized");

                    b.HasIndex("Rating");

                    b.HasIndex("StudioId");

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageGallery", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId", "GalleryId");

                    b.HasIndex("GalleryId");

                    b.ToTable("image_galleries", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.ImagePerformer", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.ToTable("image_performers", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageTag", b =>
                {
                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ImageId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("image_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CareerEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CareerStart")
                        .HasColumnType("date");

                    b.Property<int?>("Circumcised")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Disambiguation")
                        .HasColumnType("text");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("text");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text");

                    b.Property<string>("FakeTits")
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("HairColor")
                        .HasColumnType("text");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<bool>("IgnoreAutoTag")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageBlobId")
                        .HasColumnType("text");

                    b.Property<string>("Measurements")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("PenisLength")
                        .HasColumnType("double precision");

                    b.Property<string>("Piercings")
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Tattoos")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Favorite");

                    b.HasIndex("Name");

                    b.HasIndex("Rating");

                    b.ToTable("performers", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("PerformerAlias");
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerRemoteId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("PerformerRemoteId", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerTag", b =>
                {
                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PerformerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("performer_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("PerformerUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.SavedFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FindFilter")
                        .HasColumnType("jsonb");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectFilter")
                        .HasColumnType("jsonb");

                    b.Property<string>("UIOptions")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("saved_filters", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OCounter")
                        .HasColumnType("integer");

                    b.Property<bool>("Organized")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<double>("PlayDuration")
                        .HasColumnType("double precision");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasAnnotation("Range", new[] { 1, 100 });

                    b.Property<double>("ResumeTime")
                        .HasColumnType("double precision");

                    b.Property<int?>("StudioId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Date");

                    b.HasIndex("Organized");

                    b.HasIndex("Rating");

                    b.HasIndex("StudioId");

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneGallery", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "GalleryId");

                    b.HasIndex("GalleryId");

                    b.ToTable("scene_galleries", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneGroup", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SceneIndex")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("scene_groups", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("PrimaryTagId")
                        .HasColumnType("integer");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<double>("Seconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTagId");

                    b.HasIndex("SceneId");

                    b.ToTable("scene_markers", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneMarkerTag", b =>
                {
                    b.Property<int>("SceneMarkerId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("SceneMarkerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("scene_marker_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneOHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneOHistory");
                });

            modelBuilder.Entity("Cove.Core.Entities.ScenePerformer", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("PerformerId")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "PerformerId");

                    b.HasIndex("PerformerId");

                    b.ToTable("scene_performers", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.ScenePlayHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("ScenePlayHistory");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneRemoteId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneRemoteId", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneTag", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("SceneId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("scene_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SceneId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IgnoreAutoTag")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageBlobId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Organized")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("studios", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioAlias");
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioRemoteId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioRemoteId", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioTag", b =>
                {
                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("StudioId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("studio_tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("StudioUrl");
                });

            modelBuilder.Entity("Cove.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("CustomFields")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IgnoreAutoTag")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageBlobId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SortName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Favorite");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.TagAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagAlias");
                });

            modelBuilder.Entity("Cove.Core.Entities.TagParent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("tag_parents", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.TagRemoteId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagRemoteId", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasFilter("\"ApiKey\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.VideoCaption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("VideoCaptions", (string)null);
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryFile", b =>
                {
                    b.HasBaseType("Cove.Core.Entities.BaseFileEntity");

                    b.Property<int?>("GalleryId")
                        .HasColumnType("integer");

                    b.HasIndex("GalleryId");

                    b.HasDiscriminator().HasValue("Gallery");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageFile", b =>
                {
                    b.HasBaseType("Cove.Core.Entities.BaseFileEntity");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("ImageId");

                    b.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("Cove.Core.Entities.VideoFile", b =>
                {
                    b.HasBaseType("Cove.Core.Entities.BaseFileEntity");

                    b.Property<string>("AudioCodec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BitRate")
                        .HasColumnType("bigint");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FrameRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("Interactive")
                        .HasColumnType("boolean");

                    b.Property<int?>("InteractiveSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("SceneId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("SceneId");

                    b.ToTable("files", t =>
                        {
                            t.Property("Format")
                                .HasColumnName("VideoFile_Format");

                            t.Property("Height")
                                .HasColumnName("VideoFile_Height");

                            t.Property("Width")
                                .HasColumnName("VideoFile_Width");
                        });

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("Cove.Core.Entities.BaseFileEntity", b =>
                {
                    b.HasOne("Cove.Core.Entities.Folder", "ParentFolder")
                        .WithMany("Files")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Cove.Core.Entities.FileFingerprint", b =>
                {
                    b.HasOne("Cove.Core.Entities.BaseFileEntity", "File")
                        .WithMany("Fingerprints")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Cove.Core.Entities.Folder", b =>
                {
                    b.HasOne("Cove.Core.Entities.Folder", "ParentFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Cove.Core.Entities.Gallery", b =>
                {
                    b.HasOne("Cove.Core.Entities.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Galleries")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Folder");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryChapter", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("Chapters")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryPerformer", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("GalleryPerformers")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("GalleryPerformers")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("GalleryTags")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("GalleryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("Urls")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Cove.Core.Entities.Group", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Groups")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupRelation", b =>
                {
                    b.HasOne("Cove.Core.Entities.Group", "ContainingGroup")
                        .WithMany("SubGroupRelations")
                        .HasForeignKey("ContainingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Group", "SubGroup")
                        .WithMany("ContainingGroupRelations")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainingGroup");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Group", "Group")
                        .WithMany("GroupTags")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("GroupTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.GroupUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Group", "Group")
                        .WithMany("Urls")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Cove.Core.Entities.Image", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Images")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageGallery", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("ImageGalleries")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Image", "Image")
                        .WithMany("ImageGalleries")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImagePerformer", b =>
                {
                    b.HasOne("Cove.Core.Entities.Image", "Image")
                        .WithMany("ImagePerformers")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("ImagePerformers")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Image", "Image")
                        .WithMany("ImageTags")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("ImageTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Image", "Image")
                        .WithMany("Urls")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerAlias", b =>
                {
                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("Aliases")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerRemoteId", b =>
                {
                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("RemoteIds")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("PerformerTags")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("PerformerTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.PerformerUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("Urls")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Cove.Core.Entities.Scene", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Scenes")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneGallery", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("SceneGalleries")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("SceneGalleries")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneGroup", b =>
                {
                    b.HasOne("Cove.Core.Entities.Group", "Group")
                        .WithMany("SceneGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("SceneGroups")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneMarker", b =>
                {
                    b.HasOne("Cove.Core.Entities.Tag", "PrimaryTag")
                        .WithMany()
                        .HasForeignKey("PrimaryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("SceneMarkers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryTag");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneMarkerTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.SceneMarker", "SceneMarker")
                        .WithMany("SceneMarkerTags")
                        .HasForeignKey("SceneMarkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneMarker");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneOHistory", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("OHistory")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.ScenePerformer", b =>
                {
                    b.HasOne("Cove.Core.Entities.Performer", "Performer")
                        .WithMany("ScenePerformers")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("ScenePerformers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.ScenePlayHistory", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("PlayHistory")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneRemoteId", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("RemoteIds")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("SceneTags")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("SceneTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("Urls")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.Studio", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioAlias", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Aliases")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioRemoteId", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("RemoteIds")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioTag", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("StudioTags")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("StudioTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.StudioUrl", b =>
                {
                    b.HasOne("Cove.Core.Entities.Studio", "Studio")
                        .WithMany("Urls")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Cove.Core.Entities.TagAlias", b =>
                {
                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("Aliases")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.TagParent", b =>
                {
                    b.HasOne("Cove.Core.Entities.Tag", "Child")
                        .WithMany("ParentRelations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cove.Core.Entities.Tag", "Parent")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cove.Core.Entities.TagRemoteId", b =>
                {
                    b.HasOne("Cove.Core.Entities.Tag", "Tag")
                        .WithMany("RemoteIds")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cove.Core.Entities.UserRole", b =>
                {
                    b.HasOne("Cove.Core.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cove.Core.Entities.VideoCaption", b =>
                {
                    b.HasOne("Cove.Core.Entities.VideoFile", "File")
                        .WithMany("Captions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Cove.Core.Entities.GalleryFile", b =>
                {
                    b.HasOne("Cove.Core.Entities.Gallery", "Gallery")
                        .WithMany("Files")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Cove.Core.Entities.ImageFile", b =>
                {
                    b.HasOne("Cove.Core.Entities.Image", "Image")
                        .WithMany("Files")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Cove.Core.Entities.VideoFile", b =>
                {
                    b.HasOne("Cove.Core.Entities.Scene", "Scene")
                        .WithMany("Files")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Cove.Core.Entities.BaseFileEntity", b =>
                {
                    b.Navigation("Fingerprints");
                });

            modelBuilder.Entity("Cove.Core.Entities.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Cove.Core.Entities.Gallery", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Files");

                    b.Navigation("GalleryPerformers");

                    b.Navigation("GalleryTags");

                    b.Navigation("ImageGalleries");

                    b.Navigation("SceneGalleries");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.Group", b =>
                {
                    b.Navigation("ContainingGroupRelations");

                    b.Navigation("GroupTags");

                    b.Navigation("SceneGroups");

                    b.Navigation("SubGroupRelations");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.Image", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ImageGalleries");

                    b.Navigation("ImagePerformers");

                    b.Navigation("ImageTags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.Performer", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("GalleryPerformers");

                    b.Navigation("ImagePerformers");

                    b.Navigation("PerformerTags");

                    b.Navigation("RemoteIds");

                    b.Navigation("ScenePerformers");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.Scene", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("OHistory");

                    b.Navigation("PlayHistory");

                    b.Navigation("RemoteIds");

                    b.Navigation("SceneGalleries");

                    b.Navigation("SceneGroups");

                    b.Navigation("SceneMarkers");

                    b.Navigation("ScenePerformers");

                    b.Navigation("SceneTags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.SceneMarker", b =>
                {
                    b.Navigation("SceneMarkerTags");
                });

            modelBuilder.Entity("Cove.Core.Entities.Studio", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Children");

                    b.Navigation("Galleries");

                    b.Navigation("Groups");

                    b.Navigation("Images");

                    b.Navigation("RemoteIds");

                    b.Navigation("Scenes");

                    b.Navigation("StudioTags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("Cove.Core.Entities.Tag", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ChildRelations");

                    b.Navigation("GalleryTags");

                    b.Navigation("GroupTags");

                    b.Navigation("ImageTags");

                    b.Navigation("ParentRelations");

                    b.Navigation("PerformerTags");

                    b.Navigation("RemoteIds");

                    b.Navigation("SceneTags");

                    b.Navigation("StudioTags");
                });

            modelBuilder.Entity("Cove.Core.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Cove.Core.Entities.VideoFile", b =>
                {
                    b.Navigation("Captions");
                });
#pragma warning restore 612, 618
        }
    }
}
