export const PERFORMER_SORT_OPTIONS: { value: string; label: string }[] = [
  { value: "name", label: "Name" },
  { value: "rating", label: "Rating" },
  { value: "scene_count", label: "Scene Count" },
  { value: "image_count", label: "Image Count" },
  { value: "gallery_count", label: "Gallery Count" },
  { value: "tag_count", label: "Tag Count" },
  { value: "career_length", label: "Career Length" },
  { value: "last_o_at", label: "Last Favorite At" },
  { value: "last_played_at", label: "Last Played At" },
  { value: "measurements", label: "Measurements" },
  { value: "o_counter", label: "Favorites" },
  { value: "play_count", label: "Play Count" },
  { value: "birthdate", label: "Birthdate" },
  { value: "height", label: "Height" },
  { value: "weight", label: "Weight" },
  { value: "created_at", label: "Created At" },
  { value: "updated_at", label: "Updated At" },
  { value: "random", label: "Random" },
];