export const SCENE_SORT_OPTIONS: { value: string; label: string }[] = [
  { value: "updated_at", label: "Updated Date" },
  { value: "created_at", label: "Added Date" },
  { value: "title", label: "Title" },
  { value: "date", label: "Date" },
  { value: "rating", label: "Rating" },
  { value: "play_count", label: "Play Count" },
  { value: "o_counter", label: "Favorites" },
  { value: "last_o_at", label: "Last Favorite Date" },
  { value: "duration", label: "Duration" },
  { value: "file_size", label: "File Size" },
  { value: "file_mod_time", label: "File Modification Time" },
  { value: "file_count", label: "File Count" },
  { value: "path", label: "Path" },
  { value: "resolution", label: "Resolution" },
  { value: "framerate", label: "Frame Rate" },
  { value: "bitrate", label: "Bitrate" },
  { value: "phash", label: "pHash" },
  { value: "tag_count", label: "Tag Count" },
  { value: "performer_count", label: "Performer Count" },
  { value: "performer_age", label: "Performer Age" },
  { value: "studio", label: "Studio" },
  { value: "code", label: "Studio Code" },
  { value: "last_played_at", label: "Last Played" },
  { value: "play_duration", label: "Play Duration" },
  { value: "resume_time", label: "Resume Time" },
  { value: "organized", label: "Organized" },
  { value: "random", label: "Random" },
];