<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AwesomeAssertions" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cove.Api\Cove.Api.csproj" />
    <ProjectReference Include="..\Cove.ApiTestFaceProvider\Cove.ApiTestFaceProvider.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cove.Core\Cove.Core.csproj" />
  </ItemGroup>

  <Target Name="CopyApiTestFaceSuggestionProvider" AfterTargets="Build">
    <ItemGroup>
      <ApiTestFaceSuggestionProviderFiles Include="$(MSBuildProjectDirectory)\..\Cove.ApiTestFaceProvider\bin\$(Configuration)\$(TargetFramework)\Cove.ApiTestFaceProvider.*" />
      <ApiTestFaceSuggestionProviderFiles Include="$(MSBuildProjectDirectory)\..\Cove.ApiTestFaceProvider\bin\$(Configuration)\$(TargetFramework)\extension.json" />
      <ApiTestFaceSuggestionProviderFiles Include="$(MSBuildProjectDirectory)\..\Cove.ApiTestFaceProvider\bin\$(Configuration)\$(TargetFramework)\api-test-asset.*" />
    </ItemGroup>

    <MakeDir Directories="$(OutputPath)face-suggestion-provider" />
    <Copy SourceFiles="@(ApiTestFaceSuggestionProviderFiles)"
      DestinationFolder="$(OutputPath)face-suggestion-provider\"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
